debug: false
management.endpoints.web.exposure.include: '*'

logging:
  level:
    com.cafejun.springboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: debug

spring:
  datasource:
    url: jdbc:postgresql://svc.sel5.cloudtype.app:32094/board
    username: root
    password: vM4So6i3rsS!@
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  thymeleaf3.decoupled-logic: true


