debug: false
management.endpoints.web.exposure.include: '*'

logging:
  level:
    com.cafejun.springboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: debug


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: uno
    password: Jsshin2440
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true


